import type { NextPage, GetServerSideProps } from "next";
import Head from "next/head";
import Feed from "../components/feed";
import CommentModal from "../components/feed/CommentModal";
import Sidebar from "../components/sidebar";
import Widgets from "../components/widgets";
import { EnumNewsArticles } from "../models/NewsArticle";
import { EnumRandomUsers } from "../models/RandomUsers";

type Props = {
  articles: EnumNewsArticles;
  randomUsers: EnumRandomUsers;
};

const Home: NextPage<Props> = ({ articles, randomUsers }) => {
  return (
    <div>
      <Head>
        <title>Twitta</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen mx-auto ">
        <Sidebar />

        <Feed />

        <Widgets articles={articles} randomUsers={randomUsers} />

        <CommentModal />
      </main>
    </div>
  );
};

export const getServerSideProps: GetServerSideProps = async () => {
  // NEWS FREE API
  const news = await fetch(
    "https://saurav.tech/NewsAPI/top-headlines/category/business/us.json"
  );
  const newsData = await news.json();

  // RANDOM USERS FREE API
  const randomUsers = await fetch(
    "https://randomuser.me/api/?results=30&inc=name,login,picture"
  );
  const usersData = await randomUsers.json();

  return {
    props: {
      articles: newsData.articles,
      randomUsers: usersData.results,
    },
  };
};

export default Home;
