import type { NextPage } from "next";
import Head from "next/head";
import Feed from "../components/feed";
import Sidebar from "../components/sidebar";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Twitta</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen max-w-7xl mx-auto ">
        <Sidebar />

        <Feed />

        {/* Widgets */}

        {/* Modal */}
      </main>
    </div>
  );
};

export default Home;
